#!/bin/bash

MACOS_PATH=~/Library/Application\ Support/Steam/steamapps/common/Stardew\ Valley/Contents/MacOS/Mods

if [ ! -d "$MACOS_PATH" ];
then
	echo "Please install SMAPI"
	exit
fi

diff -rq "$MACOS_PATH" Mods --exclude=ConsoleCommands --exclude=SaveBackup
if [ $? -eq 1 ];
then
	echo "Update Mods"

	read -rp "Update remote or local: " type
	if [ "$type" = "local" ];
	then
		cp -r Mods/* "$MACOS_PATH"
	elif [ "$type" = "remote" ]
	then
		cp -r "$MACOS_PATH"/* Mods/
		rm -r Mods/ConsoleCommands Mods/SaveBackup
	fi
else
	echo "Mods are up to date"
fi
